# Generated by Django 6.0.6 on 2026-06-23 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('loai_nha', models.CharField(choices=[('CH', 'Chung cư'), ('NP', 'Nhà phố'), ('ĐN', 'Đất nền')], default='NP', max_length=2, verbose_name='Loại nhà')),
                ('dia_chi', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('gia', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá (VND)')),
                ('dien_tich', models.FloatField(verbose_name='Diện tích (m²)')),
                ('mo_ta', models.TextField(verbose_name='Mô tả chi tiết')),
                ('hinh_anh', models.ImageField(upload_to='properties/', verbose_name='Hình ảnh')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đăng')),
            ],
        ),
    ]
